### ISSUE TITLE
[Bug] Cuenta de FaableAuth se queda cargando

### ISSUE THREAD

**Issue by DanielDls-exe** [faablecloud/faable#2]
### Describe the bug

A la hora de estar en el apartado de FaableAuth y dirigirme a una cuenta como por ejemplo "JuanPablo Test" se queda en el logo de Faable cargando y nunca accede a la información de la misma. 

### Steps to reproduce the behavior

1. Ir a Faable Auth
2. Seleccionar una cuenta 
3. Se queda cargando 

### Also tell us, what did you expect to happen?

Debería de cargar la información de la cuenta

### Browser / OS

Chrome 127.0.6533.122

### If applicable, add screenshots to help explain your problem.

![image](https://github.com/user-attachments/assets/f209da86-2a3a-4a53-8031-3739d5544f01)

**Comment by boyander** [comment]
Fix: now is mandatory to select a team prior to access a service.
1. User tries to access `/<service>` without team in path parameter
2. User is redirected to `/dashboard`
3. User selects a team and is redirected to `/<service>/<team_id>`

@DanielDls-exe 
- [ ] repite la prueba para ver que tal va ahora
- [ ] abre otra issue de un problema relacionado, acceder a una url con un team que no existe o es inválido debe devolver una página de error. Ejemplo `https://faable.com/deploy/123412341/app`

**Comment by boyander** [comment]
Nota: 
La url `https://faable.com` tiene un caché del CDN de 1hora para hacer QA mejor usar la url `https://landing.faable.link/` que no tiene caché y se despliega instantaneamente.

**Comment by DanielDls-exe** [comment]
Va bien en caso de que no se pase un team va al /dashboard. Pero me parece que no estoy asociado a ningún team que pueda acceder a Auth

**Comment by boyander** [comment]
Porfa añade captura

**Comment by DanielDls-exe** [comment]
El id de usuario de mi cuenta es: user_65d8ad6ca28e0817c7fdbd94 

De qué se necesita captura exactamente?

**Comment by boyander** [comment]
Deberias poder entrar a auth desde cualquier team. Haz captura de los teams y dime en cuales puedes entrar a auth y cuales no

**Comment by DanielDls-exe** [comment]
![image](https://github.com/user-attachments/assets/922014f7-efc1-4d1f-9c93-363b6e6f129d)

Sí por ejemplo con el team de Kirbic entro reemplazando el deploy por auth

https://faable.com/auth/team_65a66324863cb24b65b5bca3/app

Me da el siguiente pantallazo:

![image](https://github.com/user-attachments/assets/8a02411a-2511-4ba6-9606-c6e465815dff)

https://faable.com/auth/team_65a66324863cb24b65b5bca3

Con el anterior enlace me muestra:

![image](https://github.com/user-attachments/assets/665d8f7b-9e2f-45da-9cf9-5845d010e53f)

Pero sigue apareciendo el servicio deploy a la derecha del team, aunque entiendo que la pantalla en la que me encuentro sí es la de Auth.

**Comment by boyander** [comment]
Vale, te acabo de dar acceso con tu `user_id` a la feature flag `productAuth`. Eso habilita y desabita el acceso a ciertos user_id para que vean el producto auth en el dashboard. Como es algo que todavía no hemos publicado, pues lo tengo ocultos.

La url son del formato `https://faable.com/<service>/<team_id>/<resource>`, por lo que la que estabas visitando:
`https://faable.com/auth/team_65a66324863cb24b65b5bca3/app`
debería dar un error tipo `resource_not found` ya que el resource `app` no forma parte del servicio `auth` sino solo de `deploy`. ¿Puedes crear otra issue con esto?

**Comment by boyander** [comment]
Cierro la issue y seguimos abriendo nuevas con mas detalles para reproducirlo en caso de que vuelva a salir
