### ISSUE TITLE
[Bug] Team invalido no muestra pantalla de error

### ISSUE THREAD

**Issue by DanielDls-exe** [faablecloud/faable#3]
### Describe the bug

Acceder a una url con un team que no existe o es inválido debe devolver una página de error.

### Steps to reproduce the behavior

Acceder a una url con un team invalido ejemplo:

https://faable.com/deploy/123412341/app

### Also tell us, what did you expect to happen?

Debería aparecer una página de error donde comunique al usuario que el team no existe, o no es valido.

### Browser / OS

Chrome 127.0.6533.122

### Source URL

https://faable.com/deploy/123412341/app

**Comment by boyander** [comment]
Listo, ya devuelve un error en vez de lanzar el error de nextjs.
